export type DocumentationCategory = 'start' | 'business' | 'technical' | 'troubleshooting' | 'reference';

export type DocumentationBlock =
  | { type: 'text'; title?: string; paragraphs: string[] }
  | { type: 'steps'; title: string; intro?: string; steps: { title: string; detail: string; result?: string }[] }
  | { type: 'checklist'; title: string; items: string[] }
  | { type: 'callout'; tone: 'note' | 'warning' | 'success'; title: string; text: string }
  | { type: 'table'; title: string; columns: string[]; rows: string[][] }
  | { type: 'code'; title: string; language: string; code: string; note?: string };

export interface DocumentationSection {
  id: string;
  category: DocumentationCategory;
  icon: string;
  title: string;
  summary: string;
  audience: string;
  minutes: number;
  keywords: string[];
  openView?: string;
  openLabel?: string;
  blocks: DocumentationBlock[];
}

export const CATEGORY_LABELS: Record<DocumentationCategory, string> = {
  start: 'Start here',
  business: 'Business tutorials',
  technical: 'Technical operations',
  troubleshooting: 'Troubleshooting and debugging',
  reference: 'Reference',
};

export const documentationSections: DocumentationSection[] = [
  {
    id: 'orientation',
    category: 'start',
    icon: 'compass',
    title: 'Ledger Link orientation',
    summary: 'Understand the workspace, the accounting model, and the safest order for daily work.',
    audience: 'Everyone',
    minutes: 8,
    keywords: ['first login', 'navigation', 'dashboard', 'daily workflow', 'basics'],
    openView: 'Home / Dashboard',
    openLabel: 'Open Home',
    blocks: [
      {
        type: 'text',
        title: 'What Ledger Link does',
        paragraphs: [
          'Ledger Link is a multi-company accounting workspace for Kenyan businesses. A customer invoice, supplier bill, payment, payroll run, or manual journal is recorded against one organization and ultimately appears in its ledger and reports.',
          'The left-hand index is the complete navigation on desktop. On a phone, Home, Sales, Banking, and Bills are always available in the bottom bar; More opens every other section. The top strip shows the company and current section. Ctrl+K opens global search and navigation.',
          'Amounts are stored in the organization base currency while invoices and bills may also retain their original foreign currency and exchange rate. Reports can display translated figures, but the base-currency ledger remains the accounting source of truth.',
        ],
      },
      {
        type: 'steps',
        title: 'First 30 minutes',
        steps: [
          { title: 'Confirm the company', detail: 'Open Settings → Companies. Check the legal name, base currency, country, KRA PIN, fiscal-year start, and address.', result: 'The active company name appears in the top strip and on statements.' },
          { title: 'Prepare accounts', detail: 'Open Accounting → Chart of accounts. If it is empty, choose the standard Kenyan chart; otherwise verify cash, bank, receivables, payables, income, VAT, and expense accounts.', result: 'Transactions have valid posting destinations.' },
          { title: 'Add parties', detail: 'Add at least one customer and one vendor. Record payment terms, currency, contact details, and KRA PIN where available.', result: 'Invoices and bills can be posted without placeholder parties.' },
          { title: 'Post a controlled example', detail: 'Create one small invoice or bill, then inspect Accounting → Journal entries and Reports → General ledger.', result: 'The document and its balanced accounting entry agree.' },
          { title: 'Invite the right people', detail: 'Open Team. Use Admin only for people who may post and manage access; use Member for read-only access.', result: 'Least-privilege access is in place.' },
        ],
      },
      {
        type: 'checklist',
        title: 'Recommended daily close',
        items: [
          'Record invoices, bills, receipts, and payroll activity for the day.',
          'Open Banking and review unmatched bank or M-Pesa lines.',
          'Check Home for overdue invoices, unpaid bills, or unmatched lines.',
          'Review the Audit log for unexpected posting or access changes.',
          'Run Profit and loss and Balance sheet for a reasonableness check before leaving the books.',
        ],
      },
      {
        type: 'callout',
        tone: 'warning',
        title: 'Never repair financial data directly in the browser',
        text: 'If a posted result is wrong, identify the source document or journal entry and correct it through an approved workflow. Direct database edits bypass audit and accounting safeguards and belong only in a controlled incident-recovery procedure.',
      },
    ],
  },
  {
    id: 'company-and-team-setup',
    category: 'start',
    icon: 'building',
    title: 'Company, currency, and team setup',
    summary: 'Create a trustworthy tenant boundary before entering financial records.',
    audience: 'Owner or admin',
    minutes: 12,
    keywords: ['company', 'organization', 'tenant', 'team', 'roles', 'currency', 'KRA PIN'],
    openView: 'Settings',
    openLabel: 'Open Settings',
    blocks: [
      {
        type: 'steps',
        title: 'Create or verify a company',
        steps: [
          { title: 'Open Settings', detail: 'Choose Settings from the Office group. The Companies tab lists every organization the signed-in user may access.' },
          { title: 'Add company details', detail: 'Select Add a company. Enter the operating name, legal name, base currency, country, KRA PIN, fiscal-year start, industry, address, city, phone, and email.' },
          { title: 'Choose base currency carefully', detail: 'The base currency is the currency of the accounting ledger. Changing display currency later does not rewrite the base ledger or historical source rates.' },
          { title: 'Open the correct books', detail: 'For an existing organization, choose Open these books. Confirm the company name in the header before posting.' },
          { title: 'Verify posting accounts', detail: 'Open Settings → Posting accounts and Accounting → Chart of accounts. Confirm that receivables, payables, and FX gain/loss accounts exist.' },
        ],
      },
      {
        type: 'table',
        title: 'Role model',
        columns: ['Role', 'Use it for', 'Effective application access'],
        rows: [
          ['Owner', 'The person accountable for the organization', 'Reads, posts, manages settings and team; the owner role cannot be reassigned from the Team screen.'],
          ['Admin', 'Accountants and trusted operators', 'Reads and posts organization data; can invite members and change roles.'],
          ['Member', 'Reviewers and read-only collaborators', 'Can read the books; write requests are rejected by the Worker authorization middleware.'],
        ],
      },
      {
        type: 'steps',
        title: 'Invite a team member',
        steps: [
          { title: 'Open Team', detail: 'Choose Team under Office, then select Invite a member.' },
          { title: 'Choose the minimum role', detail: 'Enter the email address and select Member unless the person must post or administer the organization.' },
          { title: 'Send and verify', detail: 'Send the invitation. Existing Ledger Link users are added immediately; new users receive an email invitation.' },
          { title: 'Audit the change', detail: 'Open Audit log and verify that the membership change identifies the expected actor and organization.' },
        ],
      },
      {
        type: 'callout',
        tone: 'note',
        title: 'Tenant isolation',
        text: 'Every organization-owned row carries an org_id. The Worker validates the access token, checks membership for the requested x-org-id, and only then runs privileged server queries. Selecting a company in the browser is never treated as authorization by itself.',
      },
    ],
  },
  {
    id: 'sales-and-receipts',
    category: 'business',
    icon: 'invoice',
    title: 'Customers, invoices, and receipts',
    summary: 'Post a sale, understand the journal effect, and record payment without overstating cash.',
    audience: 'Owner, admin, accountant',
    minutes: 15,
    keywords: ['customer', 'invoice', 'receivables', 'payment', 'sales', 'foreign currency'],
    openView: 'Sales',
    openLabel: 'Open Sales',
    blocks: [
      {
        type: 'steps',
        title: 'Create and post an invoice',
        steps: [
          { title: 'Add the customer', detail: 'Open Customers → Add customer. Record the display name, legal details, contact information, terms, currency, credit limit, and KRA PIN as applicable.' },
          { title: 'Start the invoice', detail: 'Open Sales → New invoice. Choose the customer, issue date, due date, and transaction currency.' },
          { title: 'Confirm the rate', detail: 'For a currency different from the company base, enter or verify the source-currency-per-base-currency rate shown by the form.' },
          { title: 'Add invoice lines', detail: 'For each line, enter a plain description, select the correct income account, and enter the amount and VAT. Use separate lines when revenue belongs to different accounts.' },
          { title: 'Review before posting', detail: 'Verify customer, dates, currency, line totals, VAT, and notes. Select Post invoice only once.' },
          { title: 'Verify accounting', detail: 'The atomic database workflow creates the invoice, its lines, a document number, and the balanced journal together. Check Sales and Accounting → Journal entries.' },
        ],
      },
      {
        type: 'steps',
        title: 'Receive a customer payment',
        steps: [
          { title: 'Open the outstanding invoice', detail: 'In Sales, locate an invoice with an amount due and choose the payment action.' },
          { title: 'Enter the receipt', detail: 'Enter the amount received and receipt date. The amount must be positive and cannot exceed the current amount due.' },
          { title: 'Choose the real deposit account', detail: 'Select the cash, bank, or M-Pesa asset account that actually received the money.' },
          { title: 'Post and reconcile', detail: 'Post payment, then match the corresponding bank or M-Pesa line in Banking when it is available.' },
          { title: 'Confirm closure', detail: 'A fully settled invoice reads Paid; a smaller receipt remains part paid. Review receivables by age in Reports.' },
        ],
      },
      {
        type: 'table',
        title: 'Expected accounting effect',
        columns: ['Event', 'Debit', 'Credit'],
        rows: [
          ['Invoice posted', 'Accounts receivable', 'Income and output VAT accounts'],
          ['Payment received', 'Selected cash or bank asset', 'Accounts receivable'],
          ['Invoice voided through an approved workflow', 'Reversal accounts', 'Reversal accounts; the original entry remains historically traceable'],
        ],
      },
      {
        type: 'callout',
        tone: 'warning',
        title: 'Do not record one receipt twice',
        text: 'Receiving payment on the invoice and separately posting the same bank line as new income duplicates cash or income. The bank line should be matched to the existing payment or source entry.',
      },
    ],
  },
  {
    id: 'bills-expenses-receipt-scan',
    category: 'business',
    icon: 'receipt',
    title: 'Bills, expenses, and receipt scanning',
    summary: 'Record supplier obligations, verify OCR output, and pay from the correct account.',
    audience: 'Owner, admin, accountant',
    minutes: 14,
    keywords: ['vendor', 'bill', 'expense', 'receipt', 'OCR', 'Gemini', 'payables'],
    openView: 'Expenses & Bills',
    openLabel: 'Open Bills and expenses',
    blocks: [
      {
        type: 'steps',
        title: 'Post a supplier bill manually',
        steps: [
          { title: 'Add the vendor', detail: 'Open Bills and expenses → Vendors → Add vendor. Capture supplier identity, KRA PIN, payment terms, and currency.' },
          { title: 'Open New bill', detail: 'Choose the supplier, expense account, bill date, due date, and currency.' },
          { title: 'Describe the purchase', detail: 'Enter particulars that an approver or auditor can understand without seeing the receipt.' },
          { title: 'Enter amount and VAT', detail: 'Enter the source-currency amount and VAT percentage. Use zero only when the purchase is exempt or non-taxable.' },
          { title: 'Post and verify', detail: 'Post the bill, then verify the payables balance and the relevant expense or asset account.' },
        ],
      },
      {
        type: 'steps',
        title: 'Read a receipt safely',
        intro: 'Receipt scanning extracts suggestions; it does not replace review.',
        steps: [
          { title: 'Choose Read a receipt', detail: 'Use the camera on a secure connection or upload a sharp, well-lit image.' },
          { title: 'Wait for extraction', detail: 'The image is sent to the authenticated /api/expenses/scan endpoint and Gemini returns vendor, amount, and date suggestions.' },
          { title: 'Review every extracted value', detail: 'Confirm vendor spelling, transaction date, gross amount, VAT treatment, expense account, and currency against the physical receipt.' },
          { title: 'Create missing vendor if needed', detail: 'If the supplier is unknown, close or preserve the reviewed values as appropriate, add the vendor, then continue the bill.' },
          { title: 'Retain evidence under company policy', detail: 'Ledger Link extracts fields but the organization remains responsible for retaining legally required source documents.' },
        ],
      },
      {
        type: 'steps',
        title: 'Pay open bills',
        steps: [
          { title: 'Open Bill payments', detail: 'Review the open-bill list and confirm each amount due.' },
          { title: 'Choose Pay from', detail: 'Select the actual cash or bank asset account. If none is available, add or reactivate the account first.' },
          { title: 'Post the payment batch', detail: 'Post these payments. Each bill is processed with its own idempotency key and accounting transaction.' },
          { title: 'Review partial failure messages', detail: 'If the result says some payments posted and others failed, refresh first. Never resubmit the entire batch without checking bill balances.' },
        ],
      },
    ],
  },
  {
    id: 'banking-reconciliation',
    category: 'business',
    icon: 'bank',
    title: 'Banking, matching, rules, and reconciliation',
    summary: 'Explain every bank or M-Pesa line without creating duplicate accounting activity.',
    audience: 'Owner, admin, accountant',
    minutes: 18,
    keywords: ['banking', 'M-Pesa', 'match', 'reconcile', 'rules', 'statement'],
    openView: 'Banking',
    openLabel: 'Open Banking',
    blocks: [
      {
        type: 'text',
        title: 'How to think about a statement line',
        paragraphs: [
          'A bank line is evidence that money moved. It may correspond to an invoice payment, a supplier payment, payroll, a transfer, a fee, or a new transaction not yet recorded. Matching links the evidence to the accounting explanation.',
          'Suggested matches are assistance, not authority. Review party, amount, direction, date, account, and confidence before accepting. Strong matches may be accepted in bulk only after the underlying source records have been reviewed.',
        ],
      },
      {
        type: 'steps',
        title: 'Review and match statement lines',
        steps: [
          { title: 'Open Statement lines', detail: 'Start with unreviewed items. Confirm the date, description, direction, and amount against the bank or M-Pesa source.' },
          { title: 'Review suggested matches', detail: 'Open Suggested matches. Compare the line to the proposed invoice, bill, or account; do not accept based on confidence alone.' },
          { title: 'Link an existing record', detail: 'Use Match this line when the invoice, bill, or journal already exists. This avoids recording the transaction twice.' },
          { title: 'Create only when genuinely missing', detail: 'If no source record exists, match to an appropriate account or create the required source transaction following approval policy.' },
          { title: 'Check Reconcile', detail: 'Review opening balance, statement activity, book activity, and difference. Investigate a non-zero difference before closing the period.' },
        ],
      },
      {
        type: 'steps',
        title: 'Use a banking rule',
        steps: [
          { title: 'Identify a repeatable description', detail: 'Choose stable text such as a known bank charge label, not a customer-specific amount or transient reference.' },
          { title: 'Add a rule', detail: 'In Rules, define the match text, direction if applicable, and destination account.' },
          { title: 'Test on a small set', detail: 'Review suggestions generated by the rule before applying broadly.' },
          { title: 'Remove unsafe rules', detail: 'Delete a rule that classifies unrelated transactions. Existing posted entries are not silently rewritten.' },
        ],
      },
      {
        type: 'callout',
        tone: 'note',
        title: 'Connection requests are not live feeds',
        text: 'The current app records bank connection requests and supports stored statement lines. Do not assume a requested connection is actively importing data until the integration is explicitly confirmed as operational.',
      },
    ],
  },
  {
    id: 'accounting-and-reports',
    category: 'business',
    icon: 'ledger',
    title: 'Accounting, budgets, and financial reports',
    summary: 'Maintain the chart, post controlled journals, and trace report figures to ledger lines.',
    audience: 'Accountant, owner, auditor',
    minutes: 20,
    keywords: ['journal', 'debit', 'credit', 'chart of accounts', 'reports', 'P&L', 'balance sheet', 'budget'],
    openView: 'Accounting',
    openLabel: 'Open Accounting',
    blocks: [
      {
        type: 'steps',
        title: 'Prepare the chart of accounts',
        steps: [
          { title: 'Start from a controlled chart', detail: 'If the chart is empty, use the standard Kenyan chart or import a reviewed CSV with Code, Name, Type, and Description.' },
          { title: 'Keep codes unique', detail: 'Each account code is unique inside the organization. Use a documented numbering convention.' },
          { title: 'Choose the accounting type correctly', detail: 'Asset, liability, equity, income, cost of sales, and expense types determine report classification and normal balance behavior.' },
          { title: 'Avoid deleting history-bearing accounts', detail: 'Deactivate or supersede accounts according to policy. Journal lines use restricted foreign keys to protect posted history.' },
        ],
      },
      {
        type: 'steps',
        title: 'Post a manual journal entry',
        steps: [
          { title: 'Document the reason', detail: 'Open Journal entries → Post an entry. Enter the date, memo, and reference that tie back to approved evidence.' },
          { title: 'Add at least two lines', detail: 'Select the accounts and enter each amount on exactly one side: debit or credit.' },
          { title: 'Balance before posting', detail: 'Total debits must equal total credits and be positive. The API and database reject an unbalanced entry.' },
          { title: 'Review the result', detail: 'Confirm the entry in Journal entries, then open General ledger and inspect each affected account.' },
        ],
      },
      {
        type: 'table',
        title: 'Report selection guide',
        columns: ['Question', 'Report', 'Interpretation'],
        rows: [
          ['Did the business make money?', 'Profit and loss', 'Income less cost of sales and expenses for the selected period.'],
          ['What does the business own and owe?', 'Balance sheet', 'Assets, liabilities, equity, and accumulated result at a date.'],
          ['Why did cash change?', 'Cash flow statement', 'Operating, investing, and financing movements derived from posted entries.'],
          ['Do debit and credit balances agree?', 'Trial balance', 'Every account balance with total debits and credits.'],
          ['Who owes us or whom do we owe?', 'Receivables or Payables by age', 'Open documents grouped by age.'],
          ['What posted to one account?', 'General ledger', 'Chronological lines with balances brought and carried forward.'],
          ['What is the VAT position?', 'VAT and eTIMS summary', 'Output tax, input tax, net position, and submission queue.'],
        ],
      },
      {
        type: 'checklist',
        title: 'Month-end review',
        items: [
          'Finish bank and M-Pesa matching and explain every remaining unmatched line.',
          'Review overdue receivables and payables, including credit notes or voids.',
          'Post approved accruals, prepayments, depreciation, FX, and corrections.',
          'Compare Trial balance totals; investigate any imbalance rather than forcing a plug entry.',
          'Review Profit and loss against budget and prior period.',
          'Review Balance sheet for negative assets, old suspense balances, and unexplained receivables or payables.',
          'Export final reports and retain the approved period package under company policy.',
        ],
      },
    ],
  },
  {
    id: 'operations-payroll-stock-projects-tax',
    category: 'business',
    icon: 'operations',
    title: 'Payroll, inventory, projects, and tax',
    summary: 'Run operational modules with the accounting and statutory checks they require.',
    audience: 'Owner, admin, accountant',
    minutes: 22,
    keywords: ['payroll', 'PAYE', 'NSSF', 'SHIF', 'housing levy', 'inventory', 'project', 'time', 'tax', 'VAT', 'eTIMS'],
    blocks: [
      {
        type: 'steps',
        title: 'Post a payroll run',
        steps: [
          { title: 'Maintain employees', detail: 'Open Payroll → Employees. Add identity, salary, currency, KRA PIN, NSSF details, department, and status. Confirm active employees only.' },
          { title: 'Choose period and pay date', detail: 'Open Pay run. The pay date selects the coded statutory rate table, so use the actual payroll date.' },
          { title: 'Review the preview', detail: 'Check gross pay, PAYE, NSSF, SHIF, Housing Levy, and net pay per employee and in total.' },
          { title: 'Post once', detail: 'Post this pay run only after approval. The atomic workflow creates the run, payslips, and balanced journal together.' },
          { title: 'Export statutory schedules', detail: 'Use Payslips and Statutory returns to review and export CSV schedules. Verify them against current legal requirements before filing.' },
        ],
      },
      {
        type: 'steps',
        title: 'Maintain inventory',
        steps: [
          { title: 'Add a stock item', detail: 'Enter SKU, name, category, cost, selling price, quantity on hand, reorder point, and the relevant income, COGS, and inventory asset accounts.' },
          { title: 'Review below-reorder items', detail: 'Use the Below reorder point tab to prioritize purchasing.' },
          { title: 'Reconcile counts', detail: 'Compare physical counts to quantity on hand. Investigate differences and post approved adjustments through the ledger.' },
        ],
      },
      {
        type: 'steps',
        title: 'Track projects and time',
        steps: [
          { title: 'Open a project', detail: 'Enter the project name, optional customer, dates, and approved budget.' },
          { title: 'Log hours', detail: 'In Hours logged, select the project, date, quarter-hour quantity, and a clear description of work.' },
          { title: 'Review budget against cost', detail: 'Use the project summary to compare budget, cost, revenue, and progress. Project tracking does not replace approved source documents.' },
        ],
      },
      {
        type: 'checklist',
        title: 'Tax and eTIMS review',
        items: [
          'Record the organization KRA PIN in Settings before preparing filings.',
          'Review Tax → VAT position against the VAT and eTIMS report and source invoices/bills.',
          'Treat eTIMS connection as unavailable until the business has KRA-issued OSCU or VSCU registration and credentials.',
          'Use the statutory calendar as an operational reminder, not legal advice; confirm current KRA and statutory deadlines.',
          'Retain exported schedules and source evidence used for the filed return.',
        ],
      },
      {
        type: 'callout',
        tone: 'warning',
        title: 'Statutory figures require human review',
        text: 'Rate tables are versioned in code and selected by effective date, but employee-specific reliefs, benefits, amendments, and legal changes may require professional review before filing or payment.',
      },
    ],
  },
  {
    id: 'security-and-access',
    category: 'business',
    icon: 'shield',
    title: 'Security and access for operators',
    summary: 'Use least privilege, protect sessions, and recognize the controls the SaaS already enforces.',
    audience: 'Owner, admin, security reviewer',
    minutes: 12,
    keywords: ['security', 'access', 'roles', 'session', 'audit', 'RLS', 'secrets'],
    openView: 'Audit Logs',
    openLabel: 'Open Audit log',
    blocks: [
      {
        type: 'checklist',
        title: 'Operator security baseline',
        items: [
          'Give every person their own account; never share passwords or a generic finance login.',
          'Assign Member unless posting or administration is required.',
          'Remove access promptly when a person changes role or leaves.',
          'Check the active company before every sensitive action in a multi-company account.',
          'Review the Audit log after role, account, journal, or bulk changes.',
          'Sign out on shared devices. The app also signs out after 15 minutes without interaction.',
          'Never paste Supabase secret keys, Gemini keys, access tokens, or customer data into chat or issue trackers.',
        ],
      },
      {
        type: 'text',
        title: 'Control layers',
        paragraphs: [
          'The browser authenticates with Supabase Auth. Same-origin /api requests receive the Bearer access token and active x-org-id through the authenticated fetch bridge.',
          'The Cloudflare Worker verifies the token against Supabase Auth, loads the user membership for the requested organization, rejects writes from members, and adds the verified user and organization to request context.',
          'Postgres row-level security scopes direct authenticated access by membership. Server-side financial workflows re-check the actor and write related document, payment, counter, and journal records atomically.',
        ],
      },
      {
        type: 'callout',
        tone: 'warning',
        title: 'A service key bypasses row-level security',
        text: 'SUPABASE_SECRET_KEY and the legacy service-role key belong only in the Worker secret store. A leaked key is a security incident: rotate it, inspect logs and audit data, and assess unauthorized access immediately.',
      },
    ],
  },
  {
    id: 'architecture',
    category: 'technical',
    icon: 'architecture',
    title: 'SaaS architecture and request lifecycle',
    summary: 'Understand the frontend, edge API, identity boundary, database, and atomic accounting layer.',
    audience: 'Developers, SRE, security',
    minutes: 16,
    keywords: ['architecture', 'React', 'Cloudflare', 'Hono', 'Supabase', 'Postgres', 'request lifecycle', 'multi tenant'],
    blocks: [
      {
        type: 'table',
        title: 'Runtime components',
        columns: ['Layer', 'Technology', 'Responsibility'],
        rows: [
          ['Client', 'React 19, TypeScript, Vite, Tailwind v4', 'Views, accessible interaction, optimistic state, report exports, authenticated API calls.'],
          ['Client state', 'Zustand and TanStack Query', 'Active organization/view/theme plus cached server state and mutation invalidation.'],
          ['Edge API', 'Hono on Cloudflare Workers', 'CORS/security headers, auth and membership checks, Zod validation, routing, error normalization.'],
          ['Domain services', 'TypeScript under src/server', 'Framework-independent queries and business operations using the server Supabase client.'],
          ['Identity', 'Supabase Auth', 'Email/password sessions and verified user lookup.'],
          ['Database', 'Supabase PostgreSQL', 'Tenant data, RLS, constraints, audit records, counters, and atomic financial functions.'],
          ['Optional AI', 'Google Gemini', 'Authenticated receipt field extraction only; no core accounting decision depends on it.'],
          ['Static delivery', 'Cloudflare Worker assets binding', 'SPA assets from dist/client with /api routed to the Worker first.'],
        ],
      },
      {
        type: 'steps',
        title: 'Organization-scoped request lifecycle',
        steps: [
          { title: 'Browser creates a request', detail: 'A component calls /api. installAuthenticatedApiFetch detects same-origin API traffic.' },
          { title: 'Headers are attached', detail: 'The bridge adds Authorization: Bearer <access token> and x-org-id from the Zustand store unless already present.' },
          { title: 'Worker verifies identity', detail: 'requireAuthenticationAndOrganization calls Supabase Auth getUser. Missing, expired, or invalid tokens return 401.' },
          { title: 'Worker verifies tenancy', detail: 'The middleware validates x-org-id as a UUID and checks memberships for the verified user. No membership returns 403.' },
          { title: 'Worker verifies write role', detail: 'For non-GET requests, only owner or admin proceeds. Member writes return 403 before the domain service runs.' },
          { title: 'Route validates input', detail: 'Zod schemas reject malformed or unsafe payloads with a client-safe 400 response.' },
          { title: 'Service executes', detail: 'The server Supabase client uses the secret key. Organization and actor values come from verified middleware context, not browser claims.' },
          { title: 'Client reconciles state', detail: 'TanStack Query invalidates affected query keys and refetches canonical state.' },
        ],
      },
      {
        type: 'text',
        title: 'Financial consistency model',
        paragraphs: [
          'Documents and their accounting entries are not written as unrelated requests. Postgres functions such as create_invoice_with_journal, create_bill_with_journal, receive_invoice_payment, pay_bill, void workflows, and run_payroll_with_journal execute the related changes in one transaction.',
          'Idempotency keys protect retryable financial operations. Journal integrity constraints and functions require positive, balanced debit and credit totals. Posted history is protected from unsafe in-place mutation; reversals preserve traceability.',
        ],
      },
    ],
  },
  {
    id: 'local-development',
    category: 'technical',
    icon: 'terminal',
    title: 'Local development and configuration',
    summary: 'Bootstrap a reproducible developer environment without exposing server credentials.',
    audience: 'Developers',
    minutes: 18,
    keywords: ['setup', 'local', 'environment', 'npm', 'Vite', 'Wrangler', 'secrets', 'configuration'],
    blocks: [
      {
        type: 'checklist',
        title: 'Prerequisites',
        items: [
          'Node.js 18 or newer and npm 9 or newer.',
          'A Supabase project with Auth enabled and permission to apply migrations.',
          'A Cloudflare account for Worker preview/deployment.',
          'A Gemini API key only when testing receipt extraction.',
          'Git access to the repository and a feature branch for changes.',
        ],
      },
      {
        type: 'code',
        title: 'Install and start',
        language: 'shell',
        code: 'git clone https://github.com/MadScie254/ledger_link_254.git\ncd ledger_link_254\nnpm install\n# PowerShell: Copy-Item .env.example .env\n# macOS/Linux: cp .env.example .env\nsupabase db push\nnpm run dev',
        note: 'Vite prints the actual local URL. The Cloudflare Vite plugin runs frontend assets and the Worker API together.',
      },
      {
        type: 'table',
        title: 'Environment variable contract',
        columns: ['Variable', 'Runtime', 'Purpose and handling'],
        rows: [
          ['SUPABASE_URL', 'Worker', 'Project URL. Non-secret but environment-specific.'],
          ['SUPABASE_SECRET_KEY', 'Worker only', 'Preferred privileged server key. Store as a local secret or Wrangler secret; never expose to Vite.'],
          ['SUPABASE_SERVICE_ROLE_KEY', 'Worker only', 'Legacy fallback during rotation only. Treat with the same sensitivity as the secret key.'],
          ['VITE_SUPABASE_URL', 'Browser', 'The same project URL compiled into the client bundle.'],
          ['VITE_SUPABASE_PUBLISHABLE_KEY', 'Browser', 'Publishable browser key. RLS and API authorization still enforce access.'],
          ['VITE_SUPABASE_ANON_KEY', 'Browser', 'Legacy publishable-key fallback.'],
          ['GEMINI_API_KEY', 'Worker only', 'Used by receipt scanning. Missing key should affect OCR only.'],
          ['ALLOWED_ORIGINS', 'Worker', 'Comma-separated exact browser origins accepted by CORS. Protocol, host, and port must match.'],
          ['NODE_ENV', 'Worker/build', 'development, production, or test behavior.'],
          ['ENABLE_SEED_DATA', 'Scripts/dev only', 'Keep false or unset in production.'],
        ],
      },
      {
        type: 'code',
        title: 'Quality gate before a pull request',
        language: 'shell',
        code: 'npm run lint\nnpm test\nnpm run build\ngit diff --check',
        note: 'Type checking is the lint gate. Tests cover calculation utilities and onboarding contracts; the production build validates both Worker and client bundles.',
      },
      {
        type: 'callout',
        tone: 'warning',
        title: 'Client prefixes are a security boundary',
        text: 'Anything prefixed VITE_ can be embedded in browser JavaScript. Never create VITE_SUPABASE_SECRET_KEY, VITE_GEMINI_API_KEY, or any VITE_ variable containing a private credential.',
      },
    ],
  },
  {
    id: 'database-and-migrations',
    category: 'technical',
    icon: 'database',
    title: 'Database, RLS, migrations, and financial integrity',
    summary: 'Change the schema safely while preserving tenant isolation and double-entry guarantees.',
    audience: 'Backend developers, DBA, security',
    minutes: 22,
    keywords: ['database', 'migration', 'RLS', 'SQL', 'Postgres', 'constraints', 'rollback', 'atomic'],
    blocks: [
      {
        type: 'text',
        title: 'Schema domains',
        paragraphs: [
          'Core identity and accounting tables include organizations, memberships, accounts, journal_entries, and journal_lines. Business documents include customers, vendors, invoices, bills, payment tables, employees, inventory_items, projects, budgets, banking rules, connection requests, payroll runs, payslips, audit logs, eTIMS submissions, and document counters.',
          'Most business tables are organization-owned through org_id. memberships is the authoritative user-to-organization relationship. user_profiles is person-scoped and currently stores durable onboarding status and step.',
        ],
      },
      {
        type: 'steps',
        title: 'Create a safe migration',
        steps: [
          { title: 'Identify invariants', detail: 'List tenant key, ownership, nullability, money representation, foreign keys, uniqueness, audit expectations, and whether existing rows need backfill.' },
          { title: 'Write forward SQL', detail: 'Add the next timestamped file under supabase/migrations. Use explicit public/private schemas and deterministic constraint names.' },
          { title: 'Backfill before enforcing', detail: 'For non-null additions, create a safe default or staged backfill, validate data, then apply the stronger constraint.' },
          { title: 'Add RLS and grants', detail: 'Enable RLS for exposed tables, add least-privilege policies, and grant only the required operations. Verify both authenticated and service roles.' },
          { title: 'Document reversal', detail: 'Include dependency-ordered rollback SQL or a forward corrective migration plan. Never drop financial history casually.' },
          { title: 'Test on disposable data', detail: 'Apply to a local or preview database with representative organizations, memberships, documents, and posted entries.' },
          { title: 'Deploy before dependent code', detail: 'When application code requires new database objects, apply compatible schema first or use an expand/migrate/contract rollout.' },
        ],
      },
      {
        type: 'checklist',
        title: 'Migration review checklist',
        items: [
          'Every organization-owned table has org_id, a foreign key, and an index where query patterns need it.',
          'RLS policy expressions use auth.uid() and membership checks correctly.',
          'Service-role functions independently validate actor membership before financial writes.',
          'Money units are explicit: database numeric amounts versus application cents must not be mixed.',
          'Document numbering remains organization-scoped and concurrency-safe.',
          'Retries cannot duplicate invoices, bills, payments, or payroll runs.',
          'Destructive changes have a backup, validation query, and rollback/forward-fix plan.',
        ],
      },
      {
        type: 'code',
        title: 'Apply and inspect migrations',
        language: 'shell',
        code: 'supabase db push\n# Review applied migration history in the target project before deployment.\n# Never run reset commands against production.',
      },
      {
        type: 'callout',
        tone: 'warning',
        title: 'Production data rule',
        text: 'Do not test rollback by dropping tables, enums, functions, or columns in production. Restore drills belong in an isolated project created from a known backup.',
      },
    ],
  },
  {
    id: 'api-contract',
    category: 'technical',
    icon: 'api',
    title: 'API, authentication, and integration contract',
    summary: 'Call the Worker safely and interpret status codes without bypassing tenancy controls.',
    audience: 'Frontend and integration developers',
    minutes: 18,
    keywords: ['API', 'Authorization', 'x-org-id', 'status codes', 'Hono', 'Zod', 'endpoint'],
    blocks: [
      {
        type: 'table',
        title: 'Request requirements',
        columns: ['Concern', 'Contract', 'Failure'],
        rows: [
          ['Authentication', 'Authorization: Bearer <Supabase access token>', '401 when missing, invalid, or expired.'],
          ['Organization scope', 'x-org-id: <organization UUID> for tenant routes', '400 when missing/malformed; 403 when membership is absent.'],
          ['Write permission', 'Owner or admin membership', '403 for member writes.'],
          ['Payload', 'application/json matching route Zod schema', '400 with a safe validation/business message.'],
          ['Unexpected server failure', 'No database internals returned to the client', '500 with a generic response; detailed error remains in Worker logs.'],
          ['Idempotency', 'UUID idempotencyKey on supported financial writes', 'Repeated safe requests resolve to the existing operation instead of duplicating it.'],
        ],
      },
      {
        type: 'code',
        title: 'Organization-scoped request example',
        language: 'http',
        code: 'GET /api/accounts HTTP/1.1\nHost: <ledger-link-origin>\nAuthorization: Bearer <supabase-access-token>\nx-org-id: <organization-uuid>\nAccept: application/json',
        note: 'Browser code should normally use the installed authenticated fetch bridge instead of manually reading token storage.',
      },
      {
        type: 'table',
        title: 'Endpoint families',
        columns: ['Family', 'Examples', 'Notes'],
        rows: [
          ['Identity/setup', '/api/onboarding, /api/organizations', 'User-scoped routes may run before an organization is selected.'],
          ['Master data', '/api/accounts, /api/customers, /api/vendors, /api/employees, /api/inventory, /api/projects', 'Tenant scoped; writes require owner/admin.'],
          ['Financial documents', '/api/invoices, /api/bills, payment subroutes, /api/payroll/runs', 'Validated and backed by atomic workflows.'],
          ['Ledger/reporting', '/api/journal-entries, /api/reports/*, /api/dashboard/metrics', 'Reports are calculated from organization data for a requested date/period.'],
          ['Banking', '/api/banking/transactions, ai-matches, match, rules, reconciliation', 'Review match intent carefully; connection request does not imply live sync.'],
          ['Governance', '/api/team, /api/audit', 'Team mutations require organization administrator middleware.'],
          ['AI', '/api/expenses/scan, /api/ai/ask', 'Optional external model dependency; results require human verification.'],
        ],
      },
      {
        type: 'checklist',
        title: 'Adding a new endpoint',
        items: [
          'Decide whether it is user-scoped or organization-scoped; default to organization-scoped.',
          'Define a strict Zod schema and reject unknown fields for writes.',
          'Take userId and orgId from verified context, never request JSON.',
          'Place database logic in a domain service or atomic SQL function, not a large route handler.',
          'Return stable, minimal response objects and client-safe errors.',
          'Invalidate only affected query keys in the client.',
          'Add tests for unauthenticated, wrong-tenant, insufficient-role, invalid-payload, success, and retry behavior.',
        ],
      },
    ],
  },
  {
    id: 'deployment-runbook',
    category: 'technical',
    icon: 'cloud',
    title: 'Cloudflare deployment runbook',
    summary: 'Promote database and application changes with validation, rollback thinking, and post-deploy checks.',
    audience: 'Developers, release manager, SRE',
    minutes: 20,
    keywords: ['deploy', 'Cloudflare', 'Wrangler', 'production', 'release', 'rollback', 'secrets'],
    blocks: [
      {
        type: 'checklist',
        title: 'Pre-deployment gate',
        items: [
          'Pull the intended main commit and verify the working tree is clean.',
          'Review migration order, backward compatibility, data backfills, and rollback/forward-fix notes.',
          'Run npm run lint, npm test, npm run build, and git diff --check.',
          'Confirm SUPABASE_URL and ALLOWED_ORIGINS target the intended environment.',
          'Confirm required Wrangler secrets exist without printing their values.',
          'Confirm ENABLE_SEED_DATA is false or unset in production.',
          'Record the commit SHA, migration set, operator, and planned validation window.',
        ],
      },
      {
        type: 'code',
        title: 'One-time authentication and secret setup',
        language: 'shell',
        code: 'npx wrangler login\nnpx wrangler secret put SUPABASE_SECRET_KEY\nnpx wrangler secret put GEMINI_API_KEY',
        note: 'Use environment-specific Cloudflare and Supabase projects. Do not paste secret values into shell history, logs, or tickets.',
      },
      {
        type: 'steps',
        title: 'Release sequence',
        steps: [
          { title: 'Back up and inspect', detail: 'Confirm the target Supabase backup/PITR posture and current migration history.' },
          { title: 'Apply compatible migrations', detail: 'Run supabase db push against the intended project. Stop on any unexpected error and do not deploy dependent code.' },
          { title: 'Build locally', detail: 'Run npm run build and inspect any new warnings, chunk changes, or Worker bundling failures.' },
          { title: 'Deploy', detail: 'Run npm run deploy. Wrangler uploads the Worker and static assets and reports the deployment URL/version.' },
          { title: 'Validate origin and CORS', detail: 'Confirm wrangler.jsonc ALLOWED_ORIGINS exactly includes the production browser origin.' },
          { title: 'Run smoke tests', detail: 'Sign in, select an organization, load Home, open one read-only report, inspect System health, and verify API requests return expected statuses.' },
          { title: 'Test one controlled write', detail: 'In a designated test organization, create and verify a small reversible/non-production transaction according to release policy.' },
          { title: 'Monitor', detail: 'Watch Worker logs, Supabase logs, error rates, latency, and support reports through the validation window.' },
        ],
      },
      {
        type: 'callout',
        tone: 'warning',
        title: 'Rollback is layer-specific',
        text: 'A Worker can be rolled back to a prior deployment, but database changes may not be safely reversible after new writes. Prefer backward-compatible migrations and a forward corrective migration over destructive schema rollback.',
      },
      {
        type: 'code',
        title: 'Build and deploy',
        language: 'shell',
        code: 'npm run lint\nnpm test\nnpm run build\nnpm run deploy',
      },
    ],
  },
  {
    id: 'observability-debugging',
    category: 'technical',
    icon: 'activity',
    title: 'Observability and systematic debugging',
    summary: 'Move from symptom to failing layer using browser, Worker, Supabase, and audit evidence.',
    audience: 'Support, developers, SRE',
    minutes: 20,
    keywords: ['debug', 'logs', 'network', 'System Health', 'Cloudflare', 'Supabase', 'monitoring'],
    openView: 'System Health',
    openLabel: 'Open System health',
    blocks: [
      {
        type: 'steps',
        title: 'Standard debugging sequence',
        steps: [
          { title: 'Define the symptom precisely', detail: 'Record user, organization, page, action, expected result, actual result, timestamp with timezone, and whether the issue is repeatable. Never collect passwords or secret keys.' },
          { title: 'Check scope', detail: 'Determine whether one record, one user, one organization, one browser, or every tenant is affected.' },
          { title: 'Inspect System health', detail: 'Open System health in the same session. Note failed API statuses, endpoint URL, duration, and the time of failure.' },
          { title: 'Inspect browser Network', detail: 'Reproduce once with DevTools open. Capture method, path, status, safe request shape, and response message. Redact Authorization and sensitive financial content.' },
          { title: 'Classify the status', detail: '401 suggests session/auth; 400 suggests headers or validation; 403 suggests membership/role; 404 suggests path/record; 409 suggests conflict/idempotency; 500 suggests Worker/service/database failure.' },
          { title: 'Correlate server evidence', detail: 'Use the timestamp and endpoint in Cloudflare logs. Follow the service call to Supabase logs, Postgres errors, or external AI errors.' },
          { title: 'Check audit and ledger impact', detail: 'Before retrying a write, confirm whether the document, payment, journal, or audit event already exists.' },
          { title: 'Fix the earliest failing layer', detail: 'Correct the root cause, add a regression test, rerun quality gates, and document the incident outcome.' },
        ],
      },
      {
        type: 'table',
        title: 'Evidence by layer',
        columns: ['Layer', 'Primary evidence', 'Typical questions'],
        rows: [
          ['Browser/UI', 'Console, Network, System health, current company', 'Did the event fire? Was the correct org selected? Was a request sent?'],
          ['Auth', 'Supabase Auth user/session and 401 response', 'Is the token present, current, and issued by the configured project?'],
          ['Authorization', 'x-org-id, membership row, role, 403 response', 'Does the verified user belong to the exact organization and have write permission?'],
          ['Worker', 'Cloudflare request/error logs', 'Which route/schema/service failed? Was the error intentionally normalized?'],
          ['Database', 'Supabase/Postgres logs, constraints, function exceptions', 'Did RLS, a constraint, or an atomic function reject the operation?'],
          ['External AI', 'Endpoint error and provider log without payload leakage', 'Is the key configured? Was the image valid? Did only the optional feature fail?'],
          ['Financial result', 'Source document, journal entry/lines, report and audit log', 'Was the operation committed once, balanced, and attributed to the correct actor?'],
        ],
      },
      {
        type: 'code',
        title: 'Local diagnostic commands',
        language: 'shell',
        code: 'npm run lint\nnpm test\nnpm run build\n# Run the integrated local frontend + Worker\nnpm run dev\n# Inspect deployed Worker logs with an authenticated Wrangler session\nnpx wrangler tail',
        note: 'Do not paste production response bodies, tokens, or financial data into public issue trackers.',
      },
      {
        type: 'callout',
        tone: 'success',
        title: 'A good bug report is reproducible and redacted',
        text: 'Include environment, commit/deployment ID, sanitized organization and record IDs, exact steps, expected/actual behavior, timestamp, endpoint/status, and whether a retry created data. Exclude credentials, access tokens, private keys, and unnecessary personal or financial data.',
      },
    ],
  },
  {
    id: 'user-troubleshooting',
    category: 'troubleshooting',
    icon: 'life-buoy',
    title: 'User troubleshooting playbook',
    summary: 'Resolve common sign-in, posting, report, payment, and receipt problems without unsafe retries.',
    audience: 'Business users and support',
    minutes: 16,
    keywords: ['troubleshoot', 'login', 'payment', 'report', 'receipt', 'blank', 'error'],
    blocks: [
      {
        type: 'table',
        title: 'Common symptoms and safe fixes',
        columns: ['Symptom', 'Check first', 'Safe resolution'],
        rows: [
          ['Cannot sign in', 'Email spelling, password, confirmation email, network, correct environment', 'Retry once. Use the account recovery/support process; do not create a second account to reach the same books.'],
          ['No company is shown', 'Whether the correct account was used and an owner/admin invited it', 'Ask an organization owner/admin to add the exact email. Refresh after acceptance.'],
          ['Save or Post is disabled', 'Required fields, account selections, dates, positive amounts, balanced journal', 'Complete the highlighted requirement. Do not alter browser state to force submission.'],
          ['Posting says permission denied', 'Team role in the active organization', 'Ask an owner/admin to perform the write or grant Admin only if the job requires it.'],
          ['Invoice payment cannot post', 'Amount is positive and no more than due; deposit account is active', 'Correct the amount/account, refresh the invoice, and try once.'],
          ['Bill payment batch partly failed', 'Which bills now show paid or reduced balances', 'Refresh and retry only the still-open bills.'],
          ['Report is empty', 'Date/period, active company, whether source documents are posted', 'Correct the period and inspect Journal entries or General ledger. Draft/unposted data may not appear.'],
          ['Report totals look wrong', 'Base/display currency, period, source document, journal lines', 'Trace the figure through General ledger; do not create a balancing plug without understanding the source.'],
          ['Receipt camera does not open', 'Browser permission, HTTPS, device camera availability', 'Allow camera access or upload a clear image instead.'],
          ['Receipt values are wrong', 'Image sharpness, lighting, currency, vendor and VAT', 'Edit every suggested field to match the receipt before posting.'],
          ['Bank difference is not zero', 'Unmatched lines, duplicate payments, opening balance, date range', 'Resolve or document each difference before period close.'],
          ['App signed out while idle', '15-minute inactivity policy', 'Sign in again. Save/review work before leaving a form unattended.'],
        ],
      },
      {
        type: 'checklist',
        title: 'Before contacting support',
        items: [
          'Refresh once and reproduce the issue once; avoid repeated financial submissions.',
          'Confirm the company name in the header and your role under Team.',
          'Record the page, action, exact visible message, and local time.',
          'Open System health and record the failing endpoint and status code.',
          'Check Audit log and the relevant list to see whether the action actually completed.',
          'Provide a sanitized record number or ID, never a password, token, or secret.',
        ],
      },
      {
        type: 'callout',
        tone: 'warning',
        title: 'Pause before retrying money movement',
        text: 'For invoices, bills, receipts, payments, payroll, and journals, first refresh and check the record and audit trail. A timeout can occur after the server commits successfully; blind retries risk duplicate business actions even when idempotency protection exists.',
      },
    ],
  },
  {
    id: 'technical-troubleshooting',
    category: 'troubleshooting',
    icon: 'bug',
    title: 'Technical troubleshooting matrix',
    summary: 'Diagnose local builds, auth headers, CORS, migrations, Worker failures, and optional AI integrations.',
    audience: 'Developers, support engineers, SRE',
    minutes: 24,
    keywords: ['401', '403', '400', '500', 'CORS', 'migration', 'build', 'Gemini', 'Supabase', 'debug'],
    blocks: [
      {
        type: 'table',
        title: 'HTTP and runtime failures',
        columns: ['Failure', 'Likely cause', 'Diagnostic', 'Fix'],
        rows: [
          ['401 Authentication is required', 'No Bearer token attached', 'Network request headers; auth session state', 'Confirm installAuthenticatedApiFetch runs before app requests and the user is signed in.'],
          ['401 Invalid or expired token', 'Expired session or client points to a different Supabase project', 'Compare configured project URLs; call Supabase getSession/getUser safely', 'Sign in again and align browser/Worker Supabase configuration.'],
          ['400 Missing x-org-id', 'No active organization or bypassed fetch bridge', 'Request headers and Zustand currentOrgId', 'Select/create a company; use fetchWithTenant/authenticated fetch for tenant routes.'],
          ['400 Invalid x-org-id', 'Placeholder, malformed, or stale organization ID', 'Inspect x-org-id format without exposing other headers', 'Remove hard-coded defaults and load a real membership organization UUID.'],
          ['403 No organization access', 'Wrong company or missing membership', 'memberships row for verified user and org', 'Correct selection or have an owner/admin add the user. Never trust a client-supplied role.'],
          ['403 Role cannot modify', 'Member attempted a write', 'Team screen and middleware orgRole', 'Use owner/admin for approved writes; keep Member read-only.'],
          ['CORS blocked', 'Browser origin absent from ALLOWED_ORIGINS', 'Console error and exact protocol/host/port', 'Add the exact origin and redeploy/restart Worker. Do not use wildcard credentials CORS.'],
          ['500 on every API route', 'Missing SUPABASE_URL or secret key', 'Worker log initialization error', 'Set correct Worker vars/secrets and redeploy. Never substitute a browser publishable key.'],
          ['Relation/function does not exist', 'Application deployed before migrations', 'Supabase/Postgres error and migration history', 'Apply the expected migrations to the correct project, then rerun smoke tests.'],
          ['Receipt scan fails only', 'Missing Gemini key, invalid image, or provider error', 'Worker log for /api/expenses/scan', 'Configure/rotate GEMINI_API_KEY or improve image; core accounting should remain available.'],
          ['Build fails in TypeScript', 'Type contract or import mismatch', 'First tsc error from npm run lint', 'Fix the earliest root type error; do not suppress with broad any or skipLibCheck as a first response.'],
          ['Deployed SPA returns 404', 'Assets or SPA fallback misconfigured', 'wrangler assets config and requested path', 'Keep dist/client assets, single-page-application fallback, and /api run_worker_first.'],
        ],
      },
      {
        type: 'steps',
        title: 'Debug a suspected duplicate financial operation',
        steps: [
          { title: 'Stop retries', detail: 'Ask the operator to stop submitting and preserve the visible error/timestamp.' },
          { title: 'Identify idempotency and source IDs', detail: 'Locate the relevant document/payment/run and its idempotency key through controlled logs or database access.' },
          { title: 'Inspect all related rows', detail: 'Check source document, line items, payments, journal entry, journal lines, counters, and audit records inside the same organization.' },
          { title: 'Confirm accounting balance', detail: 'Verify each journal is individually balanced and that source totals equal accounting totals.' },
          { title: 'Determine commit boundaries', detail: 'Atomic functions should commit all related records or none. Partial legacy data indicates a separate defect or historical workflow.' },
          { title: 'Correct through supported workflows', detail: 'Prefer void/reversal or a reviewed corrective migration. Do not delete posted journal history.' },
          { title: 'Add a regression test', detail: 'Test initial success, network retry with same key, conflicting retry, and concurrent requests.' },
        ],
      },
      {
        type: 'code',
        title: 'Configuration sanity check',
        language: 'shell',
        code: 'npm run lint\nnpm test\nnpm run build\nnpx wrangler whoami\n# Review configured variable names without printing secret values.\nnpx wrangler secret list',
      },
    ],
  },
  {
    id: 'incident-recovery',
    category: 'troubleshooting',
    icon: 'siren',
    title: 'Incident response and data recovery',
    summary: 'Contain security or financial integrity incidents and recover with an auditable process.',
    audience: 'Incident commander, SRE, finance owner',
    minutes: 18,
    keywords: ['incident', 'recovery', 'backup', 'breach', 'duplicate', 'integrity', 'restore'],
    blocks: [
      {
        type: 'steps',
        title: 'Incident response sequence',
        steps: [
          { title: 'Declare and assign', detail: 'Name an incident commander, finance decision owner, technical lead, scribe, severity, affected environment, and start time.' },
          { title: 'Contain safely', detail: 'Pause the affected feature or deployment path. For credential exposure, rotate/revoke the credential and preserve logs. Avoid destructive cleanup.' },
          { title: 'Preserve evidence', detail: 'Capture deployment IDs, sanitized request IDs, logs, audit records, timestamps, migration history, and impacted organization/record IDs under access control.' },
          { title: 'Assess scope', detail: 'Determine tenants, users, records, financial periods, confidentiality, integrity, and availability impact.' },
          { title: 'Choose recovery method', detail: 'Use an application reversal, forward corrective migration, Worker rollback, credential rotation, or isolated database restore based on the failing layer.' },
          { title: 'Validate accounting and access', detail: 'Reconcile source documents to journals and reports, verify tenant isolation, and obtain finance approval before reopening writes.' },
          { title: 'Communicate and learn', detail: 'Provide factual updates, meet legal/customer notification duties, record root cause, and track prevention work to completion.' },
        ],
      },
      {
        type: 'table',
        title: 'Recovery decision guide',
        columns: ['Scenario', 'Preferred response', 'Avoid'],
        rows: [
          ['Bad frontend/Worker release; schema compatible', 'Roll back Worker deployment and monitor', 'Changing production data to fit broken UI.'],
          ['Bad but unused additive migration', 'Forward correction or carefully reviewed rollback', 'Dropping objects without dependency and backup review.'],
          ['Incorrect posted transaction', 'Void/reverse and repost correctly', 'Deleting journal entries or editing lines in place.'],
          ['Leaked server secret', 'Rotate immediately, redeploy, review access/logs, assess notification', 'Only removing the secret from Git history while leaving it active.'],
          ['Widespread destructive data event', 'Contain writes and restore into an isolated environment for validation', 'Overwriting production immediately with an unverified backup.'],
        ],
      },
      {
        type: 'checklist',
        title: 'Recovery acceptance criteria',
        items: [
          'Affected users and organizations are explicitly enumerated.',
          'No unauthorized cross-tenant access remains possible.',
          'Documents, payments, and journal entries reconcile and remain auditable.',
          'Trial balance agrees and key reports pass finance review.',
          'The fix has automated regression coverage and deployment evidence.',
          'Credentials are rotated where exposure was possible.',
          'Incident notes and customer/legal actions are retained under policy.',
        ],
      },
    ],
  },
  {
    id: 'reference',
    category: 'reference',
    icon: 'book',
    title: 'Reference: navigation, terminology, and safe support data',
    summary: 'Quickly find keyboard commands, definitions, status meanings, and escalation details.',
    audience: 'Everyone',
    minutes: 10,
    keywords: ['reference', 'shortcut', 'glossary', 'status', 'support', 'terms'],
    blocks: [
      {
        type: 'table',
        title: 'Keyboard navigation',
        columns: ['Keys', 'Action'],
        rows: [
          ['Ctrl+K', 'Open the command palette to find a page or record.'],
          ['1', 'Open Home.'],
          ['2', 'Open Sales.'],
          ['3', 'Open Bills and expenses.'],
          ['4', 'Open Banking.'],
          ['5', 'Open Accounting.'],
          ['6', 'Open Reports.'],
          ['Tab / Shift+Tab', 'Move through interactive controls and dialog focus traps.'],
          ['Escape', 'Close the topmost dialog; during the tutorial, open skip confirmation.'],
          ['Left / Right arrow in tutorial', 'Move backward or forward through tutorial steps.'],
        ],
      },
      {
        type: 'table',
        title: 'Accounting glossary',
        columns: ['Term', 'Plain-language meaning'],
        rows: [
          ['Accounts receivable', 'Money customers still owe the business.'],
          ['Accounts payable', 'Money the business still owes suppliers.'],
          ['Debit / credit', 'The two sides of a journal entry; every posted entry must balance. They do not simply mean plus and minus.'],
          ['Journal entry', 'The dated, balanced accounting record behind a business event.'],
          ['General ledger', 'Every posted line for each account, in date order.'],
          ['Trial balance', 'A list of account balances whose total debits and credits should agree.'],
          ['Reconciliation', 'Explaining statement activity by matching it to accounting records and resolving differences.'],
          ['Base currency', 'The currency in which the organization keeps its accounting ledger.'],
          ['Unrealized FX', 'Exchange-rate gain or loss on a foreign amount that is still open.'],
          ['Idempotency key', 'A unique request key that lets a retry resolve without duplicating a financial operation.'],
          ['RLS', 'Postgres row-level security that restricts which rows an authenticated user may access.'],
        ],
      },
      {
        type: 'table',
        title: 'Safe escalation package',
        columns: ['Include', 'Do not include'],
        rows: [
          ['Environment and deployment/commit ID', 'Passwords or password screenshots'],
          ['Timestamp with timezone and page/action', 'Authorization headers or access tokens'],
          ['Sanitized organization and record IDs', 'Supabase secret/service-role keys'],
          ['Exact visible error and HTTP status', 'Gemini API keys'],
          ['Reproduction steps and expected/actual result', 'Full customer financial exports unless an approved secure channel requires them'],
          ['Whether the write appears in Audit log or lists', 'Unredacted personal information unrelated to the issue'],
        ],
      },
      {
        type: 'callout',
        tone: 'note',
        title: 'Documentation scope',
        text: 'This page documents behavior implemented in this repository. A feature described as a request, draft, or prerequisite is not a live integration. Tax and payroll guidance explains software operation and does not replace professional or legal advice.',
      },
    ],
  },
];

export function searchableSectionText(section: DocumentationSection): string {
  const blockText = section.blocks.flatMap((block) => {
    if (block.type === 'text') return [block.title || '', ...block.paragraphs];
    if (block.type === 'steps') return [block.title, block.intro || '', ...block.steps.flatMap((step) => [step.title, step.detail, step.result || ''])];
    if (block.type === 'checklist') return [block.title, ...block.items];
    if (block.type === 'callout') return [block.title, block.text];
    if (block.type === 'table') return [block.title, ...block.columns, ...block.rows.flat()];
    return [block.title, block.language, block.code, block.note || ''];
  });
  return [section.title, section.summary, section.audience, ...section.keywords, ...blockText].join(' ').toLowerCase();
}
