-- Historical Ledger-Link production migration 20260915151655_add_budgets_table.
-- The equivalent schema is created by supabase/migrations/20260915151627_add_budgets_table.sql.
-- This marker keeps production and repository migration versions in sync
-- without replaying the same schema change twice.
